### ISSUE TITLE
Failed calling teardownTest

### ISSUE THREAD

**Issue by zhouxiangfeng** [apache/jmeter#5732]
JMeter-version：5.4.1

2022-11-09 20:01:43 WARN StandardJMeterEngine Error encountered during shutdown of org.apache.jmeter.visualizers.backend.BackendListener@36b270f6
Failed calling teardownTest
java.lang.IllegalStateException
 at org.apache.jmeter.visualizers.backend.BackendListener.testEnded(BackendListener.java:377)
 at org.apache.jmeter.visualizers.backend.BackendListener.testEnded(BackendListener.java:383)
 at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfEnd(StandardJMeterEngine.java:218)
 at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:493)
 at java.lang.Thread.run(Thread.java:748)

**Comment by vlsi** [comment]
There should be `caused by` part of the exception. Would you please copy it?
