### ISSUE TITLE
OpenModelThreadGroupController cannot be cast to LoopController

### ISSUE THREAD

**Issue by mwasplund** [apache/jmeter#5759]
### Expected behavior

Using new Open Model Thread Group throws exception when there are lot of threads to hit the target RPS value.

### Actual behavior

```
2023-01-09 22:38:03,363 ERROR o.a.j.t.JMeterThread: Test failed!
java.lang.ClassCastException: org.apache.jmeter.threads.openmodel.OpenModelThreadGroupController cannot be cast to org.apache.jmeter.control.LoopController
	at org.apache.jmeter.threads.AbstractThreadGroup.startNextLoop(AbstractThreadGroup.java:171) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.continueOnThreadLoop(JMeterThread.java:434) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.triggerLoopLogicalActionOnParentControllers(JMeterThread.java:372) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:282) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.openmodel.OpenModelThreadGroup$ThreadsStarter.run$lambda-0(OpenModelThreadGroup.kt:128) ~[ApacheJMeter_core.jar:5.5]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_351]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_351]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:1.8.0_351]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:1.8.0_351]
	at java.lang.Thread.run(Unknown Source) ~[?:1.8.0_351]
2023-01-09 22:38:03,363 INFO o.a.j.t.JMeterThread: Thread finished: Open Model Thread Group 1-248678
```

### Steps to reproduce the problem

Note: Repro is on our internal service that cannot be shared here. Hopefully this is enough info.
* Create new test plan with Open Model Thread Group.
* Set target RPS to a value that will create heavy load
* As the threads increase over time it works fine until it hits a peak concurrent load that starts to throw the above exception.

### JMeter Version

5.5

### Java Version

java version "1.8.0_351" Java(TM) SE Runtime Environment (build 1.8.0_351-b10) Java HotSpot(TM) 64-Bit Server VM (build 25.351-b10, mixed mode)

### OS Version

Windows 11 22621.963

**Comment by vlsi** [comment]
This has been fixed in https://github.com/apache/jmeter/pull/717, the fix will be released in 5.6
