### ISSUE TITLE
Can't build, The following files have format violations

### ISSUE THREAD

**Issue by ttaolu** [apache/jmeter#5794]
### Expected behavior

gradlew tasks run success

### Actual behavior

when run gradle task, the following files have format violations
 1. **`build.gradle.kts`**
 2. **`settings.gradle.kts`**
![image](https://user-images.githubusercontent.com/82750254/227522873-01603f3e-1950-4c76-b4f4-8376ed41b616.png)

```
$ `git fetch`
$ `git status`
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, **working tree clean**
```
```
$ **./gradlew buid**
> Configure project :buildSrc
Multiple files present for artifact org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.7.10: D:\Gradle\GradleUserHome\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-gradle-plugin-api\1.7.10\3b38be7ed8f8c678b13991d5b3ec99c4908d3313\kotlin-gradle-plugin-api-1.7.10-gradle70.jar and D:\Gradle\GradleUserHome\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-gradle-plugin-api\1.7.10\3b38be7ed8f8c678b13991d5b3ec99c4908d3313\kotlin-gradle-plugin-api-1.7.10.jar

> Task :buildSrc:batchtest:compileKotlin UP-TO-DATE
Multiple files present for artifact org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.7.10: D:\Gradle\GradleUserHome\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-gradle-plugin-api\1.7.10\3b38be7ed8f8c678b13991d5b3ec99c4908d3313\kotlin-gradle-plugin-api-1.7.10-gradle70.jar and D:\Gradle\GradleUserHome\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-gradle-plugin-api\1.7.10\3b38be7ed8f8c678b13991d5b3ec99c4908d3313\kotlin-gradle-plugin-api-1.7.10.jar

> Task **:buildSrc:autostyleKotlinGradleCheck** FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task '`:buildSrc:autostyleKotlinGradleCheck`'.
> The following files have format violations:
    **build.gradle.kts**

    **settings.gradle.kts**

  You might want to adjust -PmaxCheckMessageLines=50
   -PmaxFilesToList=10
   -PminLinesPerFile=4
   to see more violations
  Run './gradlew autostyleApply' to fix the violations.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
12 actionable tasks: 1 executed, 11 up-to-date

```

```
$ `git log -1`
commit 95ccef20bcf845a937ba242a0f9b2e1790aadefa (HEAD -> master, origin/master, origin/HEAD)
Author: Felix Schumacher <felix.schumacher@internetallee.de>
Date:   Mon Feb 20 15:07:13 2023 +0100

    Issue 5694: Log a warning if 'u' is found in time functions format string

    A warning will be logged,  if the code 'u' is found in the format string,
    as the meaning for that code has changed from day-of-week to year.

    Part of #5694
```

### Steps to reproduce the problem
0, i
1, git clone https://github.com/apache/jmeter.git
2, cd jmeter
3, git checkout 95ccef20b 
  the last master
4, ./graldew build
`./gradlew help --task build`
build or other task (tasks, ) run with execution failed for task ':buildSrc:autostyleKotlinGradleCheck'
### JMeter Version

5.5

### Java Version

java version "11.0.17" 2022-10-18 LTS Java(TM) SE Runtime Environment 18.9 (build 11.0.17+10-LTS-269) Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.17+10-LTS-269, mixed mode)

### OS Version
(win11)
Microsoft Windows [Version 10.0.22621.1265]

**Comment by vlsi** [comment]
Try running the build with -PmaxCheckMessageLines=500 -PmaxFilesToList=10 -PminLinesPerFile=40

**Comment by ttaolu** [comment]
not work
```
$ ./gradlew build -PmaxCheckMessageLines=500 -PmaxFilesToList=10 -PminLinesPerFile=40
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

> Configure project :buildSrc
Multiple files present for artifact org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.7.10: D:\Gradle\GradleUserHome\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-gradle-plugin-api\1.7.10\3b38be7ed8f8c678b13991d5b3ec99c4908d3313\kotlin-gradle-plugin-api-1.7.10-gradle70.jar and D:\Gradle\GradleUserHome\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-gradle-plugin-api\1.7.10\3b38be7ed8f8c678b13991d5b3ec99c4908d3313\kotlin-gradle-plugin-api-1.7.10.jar

> Task :buildSrc:batchtest:compileKotlin UP-TO-DATE
Multiple files present for artifact org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.7.10: D:\Gradle\GradleUserHome\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-gradle-plugin-api\1.7.10\3b38be7ed8f8c678b13991d5b3ec99c4908d3313\kotlin-gradle-plugin-api-1.7.10-gradle70.jar and D:\Gradle\GradleUserHome\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-gradle-plugin-api\1.7.10\3b38be7ed8f8c678b13991d5b3ec99c4908d3313\kotlin-gradle-plugin-api-1.7.10.jar

> Task :buildSrc:autostyleKotlinGradleCheck FAILED
checksum-dependency elapsed time: 1625ms, configurations processed: 13 (add -PchecksumTimingsPrint to print detailed timings)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildSrc:autostyleKotlinGradleCheck'.
> The following files have format violations:
    build.gradle.kts

    settings.gradle.kts

  You might want to adjust -PmaxCheckMessageLines=500
   -PmaxFilesToList=10
   -PminLinesPerFile=40
   to see more violations
  Run './gradlew autostyleApply' to fix the violations.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
12 actionable tasks: 1 executed, 11 up-to-date
```

**Comment by vlsi** [comment]
Does gradlew autostyleApply resolve the issue?

**Comment by ttaolu** [comment]
no, that was I run autostyleApply , 
```
$ ./gradlew autostyleApply --stacktrace
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8


> Configure project :buildSrc
Multiple files present for artifact org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.7.10: D:\Gradle\GradleUserHome\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-gradle-plugin-api\1.7.10\3b38be7ed8f8c678b13991d5b3ec99c4908d3313\kotlin-gradle-plugin-api-1.7.10-gradle70.jar and D:\Gradle\GradleUserHome\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-gradle-plugin-api\1.7.10\3b38be7ed8f8c678b13991d5b3ec99c4908d3313\kotlin-gradle-plugin-api-1.7.10.jar

> Task :buildSrc:batchtest:compileKotlin UP-TO-DATE
Multiple files present for artifact org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.7.10: D:\Gradle\GradleUserHome\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-gradle-plugin-api\1.7.10\3b38be7ed8f8c678b13991d5b3ec99c4908d3313\kotlin-gradle-plugin-api-1.7.10-gradle70.jar and D:\Gradle\GradleUserHome\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-gradle-plugin-api\1.7.10\3b38be7ed8f8c678b13991d5b3ec99c4908d3313\kotlin-gradle-plugin-api-1.7.10.jar

> Task :buildSrc:autostyleKotlinGradleCheck FAILED
> Task :buildSrc:batchtest:autostyleKotlinCheck FAILED
checksum-dependency elapsed time: 1087ms, configurations processed: 13 (add -PchecksumTimingsPrint to print detailed timings)

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':buildSrc:autostyleKotlinGradleCheck'.
> The following files have format violations:
    build.gradle.kts

    settings.gradle.kts

  You might want to adjust -PmaxCheckMessageLines=50
   -PmaxFilesToList=10
   -PminLinesPerFile=4
   to see more violations
  Run './gradlew autostyleApply' to fix the violations.

* Try:
> Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':buildSrc:autostyleKotlinGradleCheck'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:142)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
...
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:379)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
Caused by: org.gradle.api.GradleException: The following files have format violations:
  build.gradle.kts

  settings.gradle.kts

You might want to adjust -PmaxCheckMessageLines=50
 -PmaxFilesToList=10
 -PminLinesPerFile=4
 to see more violations
Run './gradlew autostyleApply' to fix the violations.
        at com.github.autostyle.gradle.AutostyleCheckTask.run(AutostyleCheckTask.kt:94)
        at jdk.internal.reflect.GeneratedMethodAccessor360.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:125)
...
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:379)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)

==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':buildSrc:batchtest:autostyleKotlinCheck'.
> The following files have format violations:
    src\main\kotlin\org\apache\jmeter\buildtools\batchtest\BatchTest.kt

  You might want to adjust -PmaxCheckMessageLines=50
   -PmaxFilesToList=10
   -PminLinesPerFile=4
   to see more violations
  Run './gradlew autostyleApply' to fix the violations.

* Try:
> Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':buildSrc:batchtest:autostyleKotlinCheck'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:142)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
  ...
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.gradle.api.GradleException: The following files have format violations:
  src\main\kotlin\org\apache\jmeter\buildtools\batchtest\BatchTest.kt

You might want to adjust -PmaxCheckMessageLines=50
 -PmaxFilesToList=10
 -PminLinesPerFile=4
 to see more violations
Run './gradlew autostyleApply' to fix the violations.
        at com.github.autostyle.gradle.AutostyleCheckTask.run(AutostyleCheckTask.kt:94)
...
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
13 actionable tasks: 2 executed, 11 up-to-date
```
any task not sucess  e.g. refresh
```
$ ./gradlew refresh -q

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildSrc:autostyleKotlinGradleCheck'.
> The following files have format violations:
    build.gradle.kts

    settings.gradle.kts

  You might want to adjust -PmaxCheckMessageLines=50
   -PmaxFilesToList=10
   -PminLinesPerFile=4
   to see more violations
  Run './gradlew autostyleApply' to fix the violations.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

```

**Comment by vlsi** [comment]
Try runing `./gradlew :buildSrc:autostyleApply`

The issue is related to `:buildSrc`, not to the main code.

**Comment by ttaolu** [comment]
same error
- ./gradlew  :buildSrc:autostyleApply
- ./gradlew  :buildSrc:autostyleApply -PmaxCheckMessageLines=50 -PmaxFilesToList=10 -PminLinesPerFile=4
- ./gradlew -PmaxCheckMessageLines=50 -PmaxFilesToList=10 -PminLinesPerFile=4 :buildSrc:autostyleApply
```groovy
$ ./gradlew -PmaxCheckMessageLines=50 -PmaxFilesToList=10 -PminLinesPerFile=4 :buildSrc:autostyleApply
> Configure project :buildSrc
Multiple files present for artifact org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.7.10: D:\Gradle\GradleUserHome\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-gradle-plugin-api\1.7.10\3b38be7ed8f8c678b13991d5b3ec99c4908d3313\kotlin-gradle-plugin-api-1.7.10-gradle70.jar and D:\Gradle\GradleUserHome\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-gradle-plugin-api\1.7.10\3b38be7ed8f8c678b13991d5b3ec99c4908d3313\kotlin-gradle-plugin-api-1.7.10.jar

> Task :buildSrc:batchtest:compileKotlin UP-TO-DATE
Multiple files present for artifact org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.7.10: D:\Gradle\GradleUserHome\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-gradle-plugin-api\1.7.10\3b38be7ed8f8c678b13991d5b3ec99c4908d3313\kotlin-gradle-plugin-api-1.7.10-gradle70.jar and D:\Gradle\GradleUserHome\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-gradle-plugin-api\1.7.10\3b38be7ed8f8c678b13991d5b3ec99c4908d3313\kotlin-gradle-plugin-api-1.7.10.jar

> Task :buildSrc:autostyleKotlinGradleCheck FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildSrc:autostyleKotlinGradleCheck'.
> The following files have format violations:
    build.gradle.kts

    settings.gradle.kts

  You might want to adjust -PmaxCheckMessageLines=50
   -PmaxFilesToList=10
   -PminLinesPerFile=4
   to see more violations
  Run './gradlew autostyleApply' to fix the violations.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
12 actionable tasks: 1 executed, 11 up-to-date

```
and why Multiple files present
thinks for help

**Comment by vlsi** [comment]
What if you change directory to `buildSrc` and issue `../gradlew autostyleApply`?

**Comment by ttaolu** [comment]
it seems ok, but what can i do next
![image](https://user-images.githubusercontent.com/82750254/226608368-6d7cda51-ec44-4829-8429-645225873322.png)
my project can not run 
![image](https://user-images.githubusercontent.com/82750254/226609567-0e26974d-5394-4005-9ebc-bcc23c1d832b.png)
run failed for all
- ../gradlew build -PmaxCheckMessageLines=50 -PmaxFilesToList=10 -PminLinesPerFile=4 (in build src)
- ../gradlew build  (in build src)
- ./gradlew build (in jmeter root)

**Comment by ttaolu** [comment]
when in buildSrc the task of clean and tasks can run success.

**Comment by vlsi** [comment]
Have you figured out what was the reason?

**Comment by ttaolu** [comment]
No, it has not been resolved. It may be a problem with my own computer or with tools or environments

**Comment by satheshshiva** [comment]
I ran faced the same error when compiling the open-telemetry library. I ran the task `./gradlew :spotlessApply` before `./gradlew build` and it fixed the issue. May be there there is a similar task in this project.
