### ISSUE TITLE
Open Model Thread Group, not able to exit http client and taking much more time than expected to exit.

### ISSUE THREAD

**Issue by heysarthak** [apache/jmeter#5819]
### Expected behavior

I am getting this error at the last requests of open model thread group, 

java.lang.InterruptedException
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1048)
	at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:230)
	at org.eclipse.jetty.client.util.FutureResponseListener.get(FutureResponseListener.java:95)
	at com.blazemeter.jmeter.http2.core.HTTP2JettyClient.send(HTTP2JettyClient.java:238)
	at com.blazemeter.jmeter.http2.core.HTTP2JettyClient.sample(HTTP2JettyClient.java:210)
	at com.blazemeter.jmeter.http2.sampler.HTTP2Sampler.sample(HTTP2Sampler.java:60)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1301)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1290)
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:651)
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:570)
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:501)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:268)
	at org.apache.jmeter.threads.openmodel.OpenModelThreadGroup$ThreadsStarter.run$lambda-0(OpenModelThreadGroup.kt:128)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
	

Open Model thread group isn't running for the said time. I ran the traffic by defining random_intervals(15 min) and it took it around 2 hours to complete.

summary = 901886 in 02:00:10 =  125.1/s Avg:  7539 Min:     0 Max: 34826 Err: 277839 (30.81%)
summary +   2098 in 00:00:27 =   77.4/s Avg:   659 Min:    17 Max: 19453 Err:    72 (3.43%) Active: 1 Started: 904076 Finished: 904075
summary = 903984 in 02:00:37 =  124.9/s Avg:  7523 Min:     0 Max: 34826 Err: 277911 (30.74%)
summary +     24 in 00:00:03 =    9.1/s Avg:    22 Min:    18 Max:    58 Err:     0 (0.00%) Active: 0 Started: 904100 Finished: 904100
summary = 904008 in 02:00:40 =  124.9/s Avg:  7523 Min:     0 Max: 34826 Err: 277911 (30.74%)
Tidying up ...    @ 2023 Apr 21 14:40:32 UTC (1682088032649)
... end of run

Also, at the end of open model thread group many HTTP client threads are on sleep mode and do not exit itself, i have to kill them manually.

1145201 jenkins   20   0   38.8g   1.5g  24080 S   0.0   1.5   0:00.00 HttpClient-3674                                                        
1145205 jenkins   20   0   38.8g   1.5g  24080 S   0.0   1.5   0:00.00 HttpClient-3674                                                        
1147190 jenkins   20   0   38.8g   1.5g  24080 S   0.0   1.5   0:00.00 HttpClient-3672                                                        
1148992 jenkins   20   0   38.8g   1.5g  24080 S   0.0   1.5   0:00.00 HttpClient-3677                                                        

### Steps to reproduce the problem

The problem is while the open model thread group gets to the end.

### JMeter Version

5.5

### OS Version

Oracle Linux

**Comment by vlsi** [comment]
Could you provide a reproducer?

**Comment by vlsi** [comment]
I think the issue is that com.blazemeter.jmeter.http2.core.HTTP2JettyClient fails to handle the interrupt properly. It should cancel the ongoing request, however it fails to do so.

I suggest raising a ticket to the plugin maintainers
