### ISSUE TITLE
Uncaught exception in thread Thread[AWT-EventQueue-0,6,main]

### ISSUE THREAD

**Issue by AlanBF1992** [apache/jmeter#5996]
### Expected behavior

Be able to save or open files

### Actual behavior

It doesn't even open the dialog option.

### Steps to reproduce the problem

Try to save or open a file.

### Log
2023-06-19 20:13:32,227 ERROR o.a.j.JMeter: Uncaught exception in thread Thread[AWT-EventQueue-0,6,main]
java.lang.ExceptionInInitializerError: null
	at org.apache.jmeter.gui.action.Load.doActionAfterCheck(Load.java:75) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.gui.action.AbstractActionWithNoRunningTest.doAction(AbstractActionWithNoRunningTest.java:44) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.gui.action.ActionRouter.performAction(ActionRouter.java:87) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.gui.action.ActionRouter.lambda$actionPerformed$0(ActionRouter.java:69) ~[ApacheJMeter_core.jar:5.5]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) ~[?:1.8.0_372]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) ~[?:1.8.0_372]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[?:1.8.0_372]
	at java.awt.EventQueue$3.run(EventQueue.java:709) ~[?:1.8.0_372]
	at java.awt.EventQueue$3.run(EventQueue.java:703) ~[?:1.8.0_372]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_372]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) ~[?:1.8.0_372]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) ~[?:1.8.0_372]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) ~[?:1.8.0_372]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) ~[?:1.8.0_372]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) ~[?:1.8.0_372]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) ~[?:1.8.0_372]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) ~[?:1.8.0_372]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) ~[?:1.8.0_372]
Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.ComparableTimSort.mergeHi(ComparableTimSort.java:866) ~[?:1.8.0_372]
	at java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:483) ~[?:1.8.0_372]
	at java.util.ComparableTimSort.mergeForceCollapse(ComparableTimSort.java:422) ~[?:1.8.0_372]
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:222) ~[?:1.8.0_372]
	at java.util.Arrays.sort(Arrays.java:1246) ~[?:1.8.0_372]
	at sun.awt.shell.Win32ShellFolderManager2.get(Win32ShellFolderManager2.java:306) ~[?:1.8.0_372]
	at sun.awt.shell.ShellFolder.get(ShellFolder.java:258) ~[?:1.8.0_372]
	at javax.swing.plaf.metal.MetalFileChooserUI$DirectoryComboBoxModel.addItem(MetalFileChooserUI.java:942) ~[?:1.8.0_372]
	at javax.swing.plaf.metal.MetalFileChooserUI$DirectoryComboBoxModel.access$800(MetalFileChooserUI.java:910) ~[?:1.8.0_372]
	at javax.swing.plaf.metal.MetalFileChooserUI.doDirectoryChanged(MetalFileChooserUI.java:659) ~[?:1.8.0_372]
	at javax.swing.plaf.metal.MetalFileChooserUI.access$1100(MetalFileChooserUI.java:53) ~[?:1.8.0_372]
	at javax.swing.plaf.metal.MetalFileChooserUI$5.propertyChange(MetalFileChooserUI.java:748) ~[?:1.8.0_372]
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335) ~[?:1.8.0_372]
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327) ~[?:1.8.0_372]
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263) ~[?:1.8.0_372]
	at java.awt.Component.firePropertyChange(Component.java:8434) ~[?:1.8.0_372]
	at javax.swing.JFileChooser.setCurrentDirectory(JFileChooser.java:598) ~[?:1.8.0_372]
	at javax.swing.JFileChooser.<init>(JFileChooser.java:344) ~[?:1.8.0_372]
	at javax.swing.JFileChooser.<init>(JFileChooser.java:296) ~[?:1.8.0_372]
	at org.apache.jmeter.gui.util.FileDialoger.<clinit>(FileDialoger.java:42) ~[ApacheJMeter_core.jar:5.5]
	... 18 more

### JMeter Version

5.5

### Java Version

openjdk version "1.8.0_372"

### OS Version

Microsoft Windows 11 Education Edition [Version 10.0.22621.1848]

### Random Data
Windows in English, but with custom locale and keyboard layout.

**Comment by vlsi** [comment]
I believe it is a jdk bug https://bugs.openjdk.org/browse/JDK-8305072

**Comment by vlsi** [comment]
I would suggest trying a different Java version like Java 17. If it does not resolve, that would mean you have a special file or directory which triggers 8305072, and I would suggest debuging jdk to figure out the problematic file/folder so the bug could be fixed in the JDK.
