### ISSUE TITLE
Why disabled csvDataSet in jmx, it still read the file in csvdataset when jmeter start to run?

### ISSUE THREAD

**Issue by linvaux** [apache/jmeter#6034]
### Expected behavior

when jmeter start to run , it should not to read the file that in csvDataSet

### Actual behavior

jmeter log print :
14:45:34.429 [测试 csv 禁用问题 1-1] ERROR org.apache.jmeter.threads.JMeterThread - Test failed!
java.lang.IllegalArgumentException: File baodu.txt must exist and be readable
	at org.apache.jmeter.services.FileServer.createBufferedReader(FileServer.java:424) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.services.FileServer.readLine(FileServer.java:340) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.config.CSVDataSet.iterationStart(CSVDataSet.java:182) ~[ApacheJMeter_components-5.4.1.jar:5.4.1]
	at org.apache.jmeter.control.GenericController.fireIterationStart(GenericController.java:399) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.control.GenericController.fireIterEvents(GenericController.java:391) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.control.GenericController.next(GenericController.java:160) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.control.LoopController.next(LoopController.java:134) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.threads.AbstractThreadGroup.next(AbstractThreadGroup.java:91) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:254) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_301]

### 1.Build a jmx file in Jmeter whit gui mode
 - 1. Create a testPlan
 - 2. Create a ThreadGroup with default config
 - 3. Create a HttpSimpler in ThreadGroup and config something 
 - 4. Add a CsvDataSet element in Threadgroup, conifg filename, vars 
 - 5. Disable this CsvDataSet element, save jmx file
### 3.Add dependencies in pom.xml
```xml
<properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <jmeter.version>5.4.1</jmeter.version>
    <hutool.version>5.8.18</hutool.version>
    <commons.compress.version>1.23.0</commons.compress.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <version>1.18.26</version>
    </dependency>
    <dependency>
      <groupId>cn.hutool</groupId>
      <artifactId>hutool-core</artifactId>
      <version>${hutool.version}</version>
    </dependency>
    <dependency>
      <groupId>cn.hutool</groupId>
      <artifactId>hutool-extra</artifactId>
      <version>${hutool.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-compress</artifactId>
      <version>${commons.compress.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.jmeter</groupId>
      <artifactId>ApacheJMeter_core</artifactId>
      <version>${jmeter.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.jmeter</groupId>
      <artifactId>ApacheJMeter_http</artifactId>
      <version>${jmeter.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.jmeter</groupId>
      <artifactId>ApacheJMeter_java</artifactId>
      <version>${jmeter.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.jmeter</groupId>
      <artifactId>ApacheJMeter_functions</artifactId>
      <version>${jmeter.version}</version>
    </dependency>
  </dependencies>
```
### 5. wirte code
```java
@Slf4j
public class App {
    public static void main(String[] args) throws Exception {
        App app = new App();
        app.initEnv();
        File jmxFile = new File("test.jmx");
        HashTree hashTree = SaveService.loadTree(jmxFile);
        StandardJMeterEngine engine = new StandardJMeterEngine();
        engine.configure(hashTree);
        engine.run();
    }

    public void initEnv() {
        String jmeterHome;
        String jmeterProperties;
        // 本地调试时，从resources下面加载
        jmeterHome = this.getClass().getResource("/").getPath() + "jmeter";
        jmeterProperties = jmeterHome + File.separator + "bin" + File.separator + "jmeter.properties";
        JMeterUtils.loadJMeterProperties(jmeterProperties);
        log.info("JMeterProperties 加载完成");
        JMeterUtils.setJMeterHome(jmeterHome);
        log.info("jmeter.home 设置完成");
        System.setProperty("jmeter.home", jmeterHome);
        JMeterUtils.setLocale(Locale.getDefault());
    }
}
```

### JMeter Version

5.4.1

### Java Version

oracle jdk1.8.0_301

### OS Version

macos 11.5.2

**Comment by vlsi** [comment]
Does it reproduce from the UI?
Does it reproduce with 5.6 or 5.6.1 rc2? (you could add a repository https://repository.apache.org/content/repositories/orgapachejmeter-1086 )

**Comment by vlsi** [comment]
Could you share the jmx?

**Comment by linvaux** [comment]
@vlsi I am so sorry, an error occurred when I uploaded the file to this issue, this text is jmx content
```xml
<?xml version="1.0" encoding="UTF-8"?>
<jmeterTestPlan version="1.2" properties="5.0" jmeter="5.4.1">
  <hashTree>
    <TestPlan guiclass="TestPlanGui" testclass="TestPlan" testname="测试计划" enabled="true">
      <stringProp name="TestPlan.comments"></stringProp>
      <boolProp name="TestPlan.functional_mode">false</boolProp>
      <boolProp name="TestPlan.tearDown_on_shutdown">true</boolProp>
      <boolProp name="TestPlan.serialize_threadgroups">false</boolProp>
      <elementProp name="TestPlan.user_defined_variables" elementType="Arguments" guiclass="ArgumentsPanel" testclass="Arguments" testname="用户定义的变量" enabled="true">
        <collectionProp name="Arguments.arguments"/>
      </elementProp>
      <stringProp name="TestPlan.user_define_classpath"></stringProp>
    </TestPlan>
    <hashTree>
      <ThreadGroup guiclass="ThreadGroupGui" testclass="ThreadGroup" testname="测试 csv 禁用问题" enabled="true">
        <stringProp name="ThreadGroup.on_sample_error">continue</stringProp>
        <elementProp name="ThreadGroup.main_controller" elementType="LoopController" guiclass="LoopControlPanel" testclass="LoopController" testname="循环控制器" enabled="true">
          <boolProp name="LoopController.continue_forever">false</boolProp>
          <intProp name="LoopController.loops">-1</intProp>
        </elementProp>
        <stringProp name="ThreadGroup.num_threads">1</stringProp>
        <stringProp name="ThreadGroup.ramp_time">1</stringProp>
        <boolProp name="ThreadGroup.scheduler">true</boolProp>
        <stringProp name="ThreadGroup.duration">30</stringProp>
        <stringProp name="ThreadGroup.delay"></stringProp>
        <boolProp name="ThreadGroup.same_user_on_next_iteration">true</boolProp>
      </ThreadGroup>
      <hashTree>
        <HTTPSamplerProxy guiclass="HttpTestSampleGui" testclass="HTTPSamplerProxy" testname="百度首页" enabled="true">
          <elementProp name="HTTPsampler.Arguments" elementType="Arguments" guiclass="HTTPArgumentsPanel" testclass="Arguments" testname="用户定义的变量" enabled="true">
            <collectionProp name="Arguments.arguments"/>
          </elementProp>
          <stringProp name="HTTPSampler.domain">www.baidu.com</stringProp>
          <stringProp name="HTTPSampler.port">443</stringProp>
          <stringProp name="HTTPSampler.protocol">https</stringProp>
          <stringProp name="HTTPSampler.contentEncoding"></stringProp>
          <stringProp name="HTTPSampler.path">/sugrec?pre=1&amp;p=3&amp;ie=utf-8&amp;json=1&amp;prod=pc&amp;from=pc_web&amp;sugsid=36555,38943,38857,38957,38956,38982,38963,38916,38801,38986,26350,38683&amp;wd=java&amp;csor=4&amp;pwd=jav&amp;cb=jQuery110208976498148756373_1688468780022&amp;_=1688468780026</stringProp>
          <stringProp name="HTTPSampler.method">GET</stringProp>
          <boolProp name="HTTPSampler.follow_redirects">true</boolProp>
          <boolProp name="HTTPSampler.auto_redirects">false</boolProp>
          <boolProp name="HTTPSampler.use_keepalive">true</boolProp>
          <boolProp name="HTTPSampler.DO_MULTIPART_POST">false</boolProp>
          <stringProp name="HTTPSampler.embedded_url_re"></stringProp>
          <stringProp name="HTTPSampler.connect_timeout"></stringProp>
          <stringProp name="HTTPSampler.response_timeout"></stringProp>
        </HTTPSamplerProxy>
        <hashTree/>
        <CSVDataSet guiclass="TestBeanGUI" testclass="CSVDataSet" testname="CSV 数据文件设置" enabled="false">
          <stringProp name="delimiter">,</stringProp>
          <stringProp name="fileEncoding">utf-8</stringProp>
          <stringProp name="filename">/data/baodu.txt</stringProp>
          <boolProp name="ignoreFirstLine">false</boolProp>
          <boolProp name="quotedData">false</boolProp>
          <boolProp name="recycle">true</boolProp>
          <stringProp name="shareMode">shareMode.all</stringProp>
          <boolProp name="stopThread">false</boolProp>
          <stringProp name="variableNames">kw</stringProp>
        </CSVDataSet>
        <hashTree/>
        <ResultCollector guiclass="ViewResultsFullVisualizer" testclass="ResultCollector" testname="察看结果树" enabled="true">
          <boolProp name="ResultCollector.error_logging">false</boolProp>
          <objProp>
            <name>saveConfig</name>
            <value class="SampleSaveConfiguration">
              <time>true</time>
              <latency>true</latency>
              <timestamp>true</timestamp>
              <success>true</success>
              <label>true</label>
              <code>true</code>
              <message>true</message>
              <threadName>true</threadName>
              <dataType>true</dataType>
              <encoding>false</encoding>
              <assertions>true</assertions>
              <subresults>true</subresults>
              <responseData>false</responseData>
              <samplerData>false</samplerData>
              <xml>false</xml>
              <fieldNames>true</fieldNames>
              <responseHeaders>false</responseHeaders>
              <requestHeaders>false</requestHeaders>
              <responseDataOnError>false</responseDataOnError>
              <saveAssertionResultsFailureMessage>true</saveAssertionResultsFailureMessage>
              <assertionsResultsToSave>0</assertionsResultsToSave>
              <bytes>true</bytes>
              <sentBytes>true</sentBytes>
              <url>true</url>
              <threadCounts>true</threadCounts>
              <idleTime>true</idleTime>
              <connectTime>true</connectTime>
            </value>
          </objProp>
          <stringProp name="filename"></stringProp>
        </ResultCollector>
        <hashTree/>
      </hashTree>
    </hashTree>
  </hashTree>
</jmeterTestPlan>

```

**Comment by vlsi** [comment]
You need to add `JMeter.convertSubTree(testTree, false);` before `engine.configure(hashTree);`

**Comment by vlsi** [comment]
See https://github.com/apache/jmeter/blob/cc7d677da9395ff0ca6d407e739e99826cf274f4/src/core/src/main/java/org/apache/jmeter/JMeter.java#L961-L972

**Comment by linvaux** [comment]
@vlsi Thank you for your help😄
