### ISSUE TITLE
standalone jmeter running on my windows pc - the connection was reset during the write operation (payload size 2.2Mb)

### ISSUE THREAD

**Issue by azizamohamedabdelsalam** [apache/jmeter#6054]
### Expected behavior

simple test plan for HTTP sampler for writing operation. with one thread (and one iteration) but the json request body size 2.2 Mb. 
 expected to run successfully specially if the same test plan configuration but with smaller payload size work successfully 

### Actual behavior

the connection was reset during the write operation, it's likely that the server closed the connection while JMeter was trying to send the request body (payload) with a size of 2,354,584 bytes.

this is part of jmeter log response :

2023-07-21 11:48:07,654 DEBUG o.a.h.wire: http-outgoing-0 >> "[write] I/O error: Software caused connection abort: socket write error"
2023-07-21 11:48:07,654 DEBUG o.a.h.i.c.DefaultManagedHttpClientConnection: http-outgoing-0: Shutdown connection
2023-07-21 11:48:07,654 DEBUG o.a.h.i.e.MainClientExec: Connection discarded
2023-07-21 11:48:07,655 DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager: Connection released: [id: 0][route: {}->http://sp-dev-qua-01.psi-mt.de:22503][total available: 0; route allocated: 0 of 2; total allocated: 0 of 20]
2023-07-21 11:48:07,655 DEBUG o.a.j.p.h.s.HTTPHC4Impl: IOException
java.net.SocketException: Connection reset by peer: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method) ~[?:?]
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110) ~[?:?]
	at java.net.SocketOutputStream.write(SocketOutputStream.java:150) ~[?:?]
	at org.apache.http.impl.conn.LoggingOutputStream.write(LoggingOutputStream.java:74) ~[httpclient-4.5.14.jar:4.5.14]
	at org.apache.http.impl.io.SessionOutputBufferImpl.streamWrite(SessionOutputBufferImpl.java:124) ~[httpcore-4.4.16.jar:4.4.16]
	at org.apache.http.impl.io.SessionOutputBufferImpl.flushBuffer(SessionOutputBufferImpl.java:136) ~[httpcore-4.4.16.jar:4.4.16]
	at org.apache.http.impl.io.SessionOutputBufferImpl.write(SessionOutputBufferImpl.java:167) ~[httpcore-4.4.16.jar:4.4.16]
	at org.apache.http.impl.io.ContentLengthOutputStream.write(ContentLengthOutputStream.java:113) ~[httpcore-4.4.16.jar:4.4.16]
	at org.apache.http.entity.FileEntity.writeTo(FileEntity.java:113) ~[httpcore-4.4.16.jar:4.4.16]
	at org.apache.http.impl.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:156) ~[httpcore-4.4.16.jar:4.4.16]
	at org.apache.http.impl.conn.CPoolProxy.sendRequestEntity(CPoolProxy.java:152) ~[httpclient-4.5.14.jar:4.5.14]
	at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:238) ~[httpcore-4.4.16.jar:4.4.16]
	at org.apache.jmeter.protocol.http.sampler.HTTPHC4Impl$2.doSendRequest(HTTPHC4Impl.java:463) ~[ApacheJMeter_http.jar:5.6.1]
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123) ~[httpcore-4.4.16.jar:4.4.16]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272) ~[httpclient-4.5.14.jar:4.5.14]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.14.jar:4.5.14]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.14.jar:4.5.14]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.14.jar:4.5.14]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.14.jar:4.5.14]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.14.jar:4.5.14]
	at org.apache.jmeter.protocol.http.sampler.HTTPHC4Impl.executeRequest(HTTPHC4Impl.java:940) ~[ApacheJMeter_http.jar:5.6.1]
	at org.apache.jmeter.protocol.http.sampler.HTTPHC4Impl.sample(HTTPHC4Impl.java:651) [ApacheJMeter_http.jar:5.6.1]
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerProxy.sample(HTTPSamplerProxy.java:66) [ApacheJMeter_http.jar:5.6.1]
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1311) [ApacheJMeter_http.jar:5.6.1]
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1300) [ApacheJMeter_http.jar:5.6.1]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:651) [ApacheJMeter_core.jar:5.6.1]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:570) [ApacheJMeter_core.jar:5.6.1]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:501) [ApacheJMeter_core.jar:5.6.1]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:268) [ApacheJMeter_core.jar:5.6.1]
	at java.lang.Thread.run(Thread.java:829) [?:?]
2023-07-21 11:48:07,662 DEBUG o.a.j.p.h.s.HTTPHC4Impl: Overwriting request old headers: 
2023-07-21 11:48:07,663 DEBUG o.a.j.a.ResponseAssertion: Test Type Info: contains=true, notTest=false, orTest=false
2023-07-21 11:48:07,663 DEBUG o.a.j.a.ResponseAssertion: Failed: 200
2023-07-21 11:48:07,674 DEBUG o.a.j.c.GenericController: Calling next on: class org.apache.jmeter.control.GenericController
2023-07-21 11:48:07,674 INFO o.a.j.t.JMeterThread: Thread is done: Thread Group 1-1
2023-07-21 11:48:07,674 INFO o.a.j.t.JMeterThread: Thread finished: Thread Group 1-1
2023-07-21 11:48:07,674 DEBUG o.a.j.p.h.s.HTTPHC4Impl: Thread Finished
2023-07-21 11:48:07,674 DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager: Connection manager is shutting down
2023-07-21 11:48:07,675 DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager: Connection manager shut down
2023-07-21 11:48:07,675 DEBUG o.a.j.t.ThreadGroup: Ending thread Thread Group 1-1
2023-07-21 11:48:07,675 INFO o.a.j.e.StandardJMeterEngine: Notifying test listeners of end of test
2023-07-21 11:48:07,675 DEBUG o.a.j.r.ResultCollector: Closing: C:\Tools\apache-jmeter-5.6.1\bin\07212023_1.jtl
2023-07-21 11:48:07,675 DEBUG o.a.j.r.ResultCollector: Closing: C:\Tools\apache-jmeter-5.6.1\bin\07212023_1
2023-07-21 11:48:07,676 DEBUG o.a.j.r.ResultCollector: Closing: C:\Tools\apache-jmeter-5.6.1\bin\log.itl
2023-07-21 11:48:07,676 INFO o.a.j.r.Summariser: summary =      1 in 00:00:02 =    0.6/s Avg:   565 Min:   565 Max:   565 Err:     1 (100.00%)
2023-07-21 11:48:07,677 DEBUG o.a.j.JMeter: jmeter.exit.check.pause is <= 0, JMeter won't check for unterminated non-daemon threads

### Steps to reproduce the problem

increase the json payload size of http reuest to size >2 Mb 

how to solve the issue of that payload can be that big size 

### JMeter Version

5.6

### Java Version

11

### OS Version

windows 10

**Comment by ravigill** [comment]
Hi Aziza, It is likely a limit on the server. You may have to check it in
the server config what the default max body size is and or it is manually
restricted.

For example for Nginx *default is 1MB *you can increase it via

http {
    ...
    client_max_body_size 100M;
}

**Comment by azizamohamedabdelsalam** [comment]
Hi Ravi,
Thank you for the reply.
Kindly i am quite new in jmeter.
How can i set this configuration for increasing max request size in the test plan.
