### ISSUE TITLE
Groovy-based tests fail with Java 22

### ISSUE THREAD

**Issue by vlsi** [apache/jmeter#6114]
### Expected behavior

JMeter tests should work with the recent Java.

Java 22 might be supported as we upgrade Groovy to 4.0.15+ (https://issues.apache.org/jira/browse/GROOVY-11197), however, it is unfortunate we can't add Java 22 testing due to failure in Groovy compilation.

### Actual behavior

```
    Execution failed for task ':src:jorphan:compileTestGroovy':
        BUG! exception in phase 'semantic analysis' in source unit '/Users/runner/work/jmeter/jmeter/src/jorphan/src/test/groovy/org/apache/jorphan/io/TextFileSpec.groovy' Unsupported class file major version 66
            at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:283)
            at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:65)
            at org.gradle.api.internal.tasks.compile.GroovyCompilerFactory$DaemonSideCompiler.execute(GroovyCompilerFactory.java:90)
            at org.gradle.api.internal.tasks.compile.GroovyCompilerFactory$DaemonSideCompiler.execute(GroovyCompilerFactory.java:76)
            at org.gradle.api.internal.tasks.compile.daemon.AbstractIsolatedCompilerWorkerExecutor$CompilerWorkAction.execute(AbstractIsolatedCompilerWorkerExecutor.java:78)
            at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
            at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:54)
            at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:48)
            at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:100)
            at org.gradle.workers.internal.AbstractClassLoaderWorker.executeInClassLoader(AbstractClassLoaderWorker.java:48)
            at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:49)
            at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:30)
            at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:96)
            at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:65)
            at org.gradle.process.internal.worker.request.WorkerAction$1.call(WorkerAction.java:138)
            at org.gradle.process.internal.worker.child.WorkerLogEventListener.withWorkerLoggingProtocol(WorkerLogEventListener.java:41)
            at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:135)
            at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
            at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
            at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
            at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
            at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
            at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
            at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
            Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 66
                at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:199)
                at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:180)
                at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:166)
                at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:287)
                ... 24 more
```

### Steps to reproduce the problem

Try running `/gradlew -PjdkBuildVersion=22 :src:jorphan:compileTestGroovy`

### JMeter Version

5.6.2

### Java Version

22

**Comment by FSchumacher** [comment]
I have trouble interpreting your message.
I understand that groovy 3.x can't be used with Java 22. Newer versions of groovy (at least alpha versions of 4.x and 5.x) could work according to the link.
What I don't get is, have you tried those? Do you think we should update to groovy 4 or later?

**Comment by vlsi** [comment]
Here is the failure: https://github.com/apache/jmeter/actions/runs/6979576352/job/18993166485?pr=6112#step:6:852

JMeter does not use Groovy for its codebase, and `groovy.jar` is just a dependency for JMeter so users can use Groovy in the scripts.

However, JMeter uses Groovy for testing purposes via Spock, and that is something that breaks testing with Java 22.
It looks like a downside of Spock for me. I am not sure we can use "the latest spock" (e.g. to support Java 22) and "still have groovy 3.0" (for backward compatibility) at the same time.

>Do you think we should update to Groovy 4 or later?

Sure we should bump Groovy in JMeter 6.0, however, we should release 5.6.3 first.

**Comment by FSchumacher** [comment]
Thanks for the explanation.

**Comment by vlsi** [comment]
Fixed in https://github.com/apache/jmeter/commit/e5355de31932ac94ce67034af07b97fddc0ff719 by migrating Groovy tests to Kotlin

**Comment by vlsi** [comment]
The issue is not fully resolved though.
Some of the batch tests use Groovy in JSR223 elements, so they do not fully work :-/

```
Logfile contents (errors during the test, see /Users/vlsi/Documents/code/jmeter/bin/FTP_TESTS.log):
2023-12-30 11:06:28,631 ERROR o.a.j.JMeter: Uncaught exception in thread Thread[#37,setUp Thread Group 1-1,5,main]
org.codehaus.groovy.GroovyBugError: BUG! exception in phase 'semantic analysis' in source unit 'Script1.groovy' Unsupported class file major version 67
        at org.codehaus.groovy.control.CompilationUnit$ISourceUnitOperation.doPhaseOperation(CompilationUnit.java:906) ~[groovy-3.0.20.jar:3.0.20]
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:628) ~[groovy-3.0.20.jar:3.0.20]
        at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:389) ~[groovy-3.0.20.jar:3.0.20]
        at groovy.lang.GroovyClassLoader.lambda$parseClass$3(GroovyClassLoader.java:332) ~[groovy-3.0.20.jar:3.0.20]
        at org.codehaus.groovy.runtime.memoize.StampedCommonCache.compute(StampedCommonCache.java:163) ~[groovy-3.0.20.jar:3.0.20]
        at org.codehaus.groovy.runtime.memoize.StampedCommonCache.getAndPut(StampedCommonCache.java:154) ~[groovy-3.0.20.jar:3.0.20]
        at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:330) ~[groovy-3.0.20.jar:3.0.20]
        at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:314) ~[groovy-3.0.20.jar:3.0.20]
        at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:257) ~[groovy-3.0.20.jar:3.0.20]
        at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.getScriptClass(GroovyScriptEngineImpl.java:336) ~[groovy-jsr223-3.0.20.jar:3.0.20]
        at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.compile(GroovyScriptEngineImpl.java:181) ~[groovy-jsr223-3.0.20.jar:3.0.20]
        at org.apache.jmeter.util.JSR223TestElement.lambda$processFileOrScript$1(JSR223TestElement.java:225) ~[ApacheJMeter_core.jar:5.6.3-SNAPSHOT]
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2406) ~[caffeine-2.9.3.jar:?]
        at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1918) ~[?:?]
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2404) ~[caffeine-2.9.3.jar:?]
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2387) ~[caffeine-2.9.3.jar:?]
        at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108) ~[caffeine-2.9.3.jar:?]
        at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62) ~[caffeine-2.9.3.jar:?]
        at org.apache.jmeter.util.JSR223TestElement.getCompiledScript(JSR223TestElement.java:252) ~[ApacheJMeter_core.jar:5.6.3-SNAPSHOT]
        at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:223) ~[ApacheJMeter_core.jar:5.6.3-SNAPSHOT]
        at org.apache.jmeter.protocol.java.sampler.JSR223Sampler.sample(JSR223Sampler.java:72) ~[ApacheJMeter_java.jar:5.6.3-SNAPSHOT]
        at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:651) ~[ApacheJMeter_core.jar:5.6.3-SNAPSHOT]
        at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:570) ~[ApacheJMeter_core.jar:5.6.3-SNAPSHOT]
        at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:501) ~[ApacheJMeter_core.jar:5.6.3-SNAPSHOT]
        at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:268) ~[ApacheJMeter_core.jar:5.6.3-SNAPSHOT]
        at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 67
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:199) ~[groovy-3.0.20.jar:3.0.20]
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:180) ~[groovy-3.0.20.jar:3.0.20]
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:166) ~[groovy-3.0.20.jar:3.0.20]
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:287) ~[groovy-3.0.20.jar:3.0.20]
        at org.codehaus.groovy.ast.decompiled.AsmDecompiler.parseClass(AsmDecompiler.java:81) ~[groovy-3.0.20.jar:3.0.20]
        at org.codehaus.groovy.control.ClassNodeResolver.findDecompiled(ClassNodeResolver.java:251) ~[groovy-3.0.20.jar:3.0.20]
        at org.codehaus.groovy.control.ClassNodeResolver.tryAsLoaderClassOrScript(ClassNodeResolver.java:189) ~[groovy-3.0.20.jar:3.0.20]
        at org.codehaus.groovy.control.ClassNodeResolver.findClassNode(ClassNodeResolver.java:169) ~[groovy-3.0.20.jar:3.0.20]
        at org.codehaus.groovy.control.ClassNodeResolver.resolveName(ClassNodeResolver.java:125) ~[groovy-3.0.20.jar:3.0.20]
        at org.codehaus.groovy.control.ResolveVisitor.resolveToOuter(ResolveVisitor.java:875) ~[groovy-3.0.20.jar:3.0.20]
        at org.codehaus.groovy.control.ResolveVisitor.resolve(ResolveVisitor.java:506) ~[groovy-3.0.20.jar:3.0.20]
        at org.codehaus.groovy.control.ResolveVisitor.visitClass(ResolveVisitor.java:1425) ~[groovy-3.0.20.jar:3.0.20]
        at org.codehaus.groovy.control.ResolveVisitor.startResolving(ResolveVisitor.java:262) ~[groovy-3.0.20.jar:3.0.20]
        at org.codehaus.groovy.control.CompilationUnit.lambda$new$16(CompilationUnit.java:739) ~[groovy-3.0.20.jar:3.0.20]
```
