### ISSUE TITLE
Constant Timer strange behavior when used with variables or functions

### ISSUE THREAD

**Issue by KingRabbid** [apache/jmeter#6162]
### Expected behavior

When the value of a Constant Timer references a variable or a function call the following must be preserved (as it happens for a numeric value):
1. Constant Timer runs after a PreProcessor
2. Constant Timer does NOT run as the 1st element in a JMX

I see a problem with current behavior:
1. Either the documentation should be clear about restriction to use anything else than numeric values and also implement a validation which rejects any other format value
2. Or fix the current issue(s)

I think Constant Timer is used by other timers (Random ones) so they may be impacted as well.

### Actual behavior

[jmeter.log](https://github.com/apache/jmeter/files/13491004/jmeter.log)
[ConstantTimer-bug.zip](https://github.com/apache/jmeter/files/13491010/ConstantTimer-bug.zip)

### Steps to reproduce the problem

Attaching sample JMX; I do recommend to set log level to DEBUG to see sequence of execution better.

### JMeter Version

5.6.2, 4.0

### Java Version

OpenJDK 64-Bit v17.0.9

### OS Version

Windows 11

**Comment by vlsi** [comment]
```
javax.script.ScriptException: javax.script.ScriptException: java.lang.NullPointerException: Cannot invoke method toLong() on null object
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:158) ~[groovy-jsr223-3.0.17.jar:3.0.17]
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:231) ~[java.scripting:?]
	at org.apache.jmeter.functions.Groovy.execute(Groovy.java:123) [ApacheJMeter_functions.jar:5.6.2-SNAPSHOT]
	at org.apache.jmeter.engine.util.CompoundVariable.execute(CompoundVariable.java:139) [ApacheJMeter_core.jar:5.6.2-SNAPSHOT]
	at org.apache.jmeter.engine.util.CompoundVariable.execute(CompoundVariable.java:114) [ApacheJMeter_core.jar:5.6.2-SNAPSHOT]
	at org.apache.jmeter.testelement.property.FunctionProperty.getStringValue(FunctionProperty.java:104) [ApacheJMeter_core.jar:5.6.2-SNAPSHOT]
	at org.apache.jmeter.testelement.property.AbstractProperty.getLongValue(AbstractProperty.java:128) [ApacheJMeter_core.jar:5.6.2-SNAPSHOT]
	at org.apache.jmeter.testelement.AbstractTestElement.getPropertyAsLong(AbstractTestElement.java:393) [ApacheJMeter_core.jar:5.6.2-SNAPSHOT]
	at org.apache.jmeter.timers.ConstantTimer.iterationStart(ConstantTimer.java:108) [ApacheJMeter_components.jar:5.6.2-SNAPSHOT]
	at org.apache.jmeter.control.GenericController.fireIterationStart(GenericController.java:412) [ApacheJMeter_core.jar:5.6.2-SNAPSHOT]
	at org.apache.jmeter.control.GenericController.fireIterEvents(GenericController.java:404) [ApacheJMeter_core.jar:5.6.2-SNAPSHOT]
```

The root cause is that constant timer evaluates delay at the "iteration start": https://github.com/apache/jmeter/blob/9b250b64c00513cbcce81fe3f12746dcde8d9ddc/src/components/src/main/java/org/apache/jmeter/timers/ConstantTimer.java#L108

It is more-or-less the same as https://github.com/apache/jmeter/issues/6165#issuecomment-1860158198

**Comment by vlsi** [comment]
The list of impacted classes is: `ConstantTimer` (and derived classes), `CompareAssertion`, `CSVDataSet`, `RandomVariableConfig`
