### ISSUE TITLE
Throw CannotResolveClassException: OpenModelThreadGroup when I use SaveService.loadTree() method load the jmx file.

### ISSUE THREAD

**Issue by wzhfeianei** [apache/jmeter#6394]
### Expected behavior

I hope use SaveService.loadTree() load contain OpenModelThreadGroup jmx file,but it throw CannotResolveClassException

### Actual behavior

throw CannotResolveClassException

### Steps to reproduce the problem

1. use jemter gui create a jmx script file it contain OpenModelThreadGroup feature 
![image](https://github.com/user-attachments/assets/03a10b08-daaa-4727-9e71-fb9d4a237b29)
2. use java program invoke SaveService.loadTree() method load the jmx file 
``` HashTree hashTree = SaveService.loadTree(scriptFile);```
4. throw Exception
java.lang.IllegalArgumentException: Problem loading XML from:'/Users/m/git/service/6760ea60488693106d67df19.jmx'. 
Cause:
CannotResolveClassException: OpenModelThreadGroup

 Detail:com.thoughtworks.xstream.converters.ConversionException: 
Debugging information 
cause-exception     : com.thoughtworks.xstream.converters.ConversionException
cause-message       : 
first-jmeter-class  : org.apache.jmeter.save.converters.HashTreeConverter.unmarshal(HashTreeConverter.java:66)
class               : org.apache.jmeter.save.ScriptWrapper
required-type       : org.apache.jmeter.save.ScriptWrapper
converter-type      : org.apache.jmeter.save.ScriptWrapperConverter
path                : /jmeterTestPlan/hashTree/hashTree/OpenModelThreadGroup
line number         : 10
version             : 5.6.3
at org.apache.jmeter.save.SaveService.readTree(SaveService.java:456)
at org.apache.jmeter.save.SaveService.loadTree(SaveService.java:429)

### JMeter Version

5.6.3

### Java Version

8

### OS Version

mac 14.6.1

**Comment by vlsi** [comment]
Is the issue still relevant?
Can you share a reproducer project?
